<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\SellFeed\Enums;

class TaskStatusEnum
{
    const S_CREATED = 'CREATED';
    const S_QUEUED = 'QUEUED';
    const S_IN_PROCESS = 'IN_PROCESS';
    const S_COMPLETED = 'COMPLETED';
    const S_COMPLETED_WITH_ERROR = 'COMPLETED_WITH_ERROR';
    const S_FAILED = 'FAILED';
    const S_PARTIALLY_PROCESSED = 'PARTIALLY_PROCESSED';
}
